AWSTemplateFormatVersion: '2010-09-09'
Description: Image Upload & Resize Pipeline using S3 + Lambda

Parameters:
  UploadBucketName:
  
    Type: String
    Description: Bucket name where users upload original images
  ProcessedBucketName:
    Type: String
    Description: Bucket name for resized images
  ArtifactBucketName:
    Type: String
    Description: S3 bucket name where the Lambda ZIP is stored
  ArtifactKey:
    Type: String
    Description: Key (path) to the Lambda ZIP in the artifact bucket

Resources:
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref UploadBucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .jpg
            Function: !GetAtt LambdaFunction.Arn

  ProcessedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ProcessedBucketName

   LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: image-processing-lambda-role-v2  # ← updated name
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaS3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub arn:aws:s3:::${UploadBucketName}/*
                  - !Sub arn:aws:s3:::${ProcessedBucketName}/*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"


  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: image-resizer
      Handler: resize.lambda_handler
      Runtime: python3.11
      Timeout: 10
      MemorySize: 256
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref ArtifactBucketName
        S3Key: !Ref ArtifactKey
      Environment:
        Variables:
          SOURCE_BUCKET: !Ref UploadBucketName
          DEST_BUCKET: !Ref ProcessedBucketName
      Layers:
        - arn:aws:lambda:eu-north-1:770693421928:layer:Klayers-p311-Pillow:1

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::${UploadBucketName}

Outputs:
  UploadBucket:
    Description: Bucket for original images
    Value: !Ref UploadBucketName

  ProcessedBucket:
    Description: Bucket for resized images
    Value: !Ref ProcessedBucketName

  LambdaFunctionName:
    Description: The name of the deployed Lambda function
    Value: !Ref LambdaFunction
