AWSTemplateFormatVersion: '2010-09-09'
Description: Image Upload & Resize Pipeline using S3 + Lambda

Parameters:
  UploadBucketName:
    Type: String
    Description: Bucket name where users upload original images
  ProcessedBucketName:
    Type: String
    Description: Bucket name for resized images
  ArtifactBucketName:
    Type: String
    Description: S3 bucket name where the Lambda ZIP is stored
  ArtifactKey:
    Type: String
    Description: Key (path) to the Lambda ZIP in the artifact bucket

Resources:

  # 🚀 1. S3 Bucket: Upload (Raw)
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref UploadBucketName

  # 📦 2. S3 Bucket: Resized Images
  ProcessedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ProcessedBucketName

  # 🔐 3. IAM Role for Lambda
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: image-processing-lambda-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaS3AccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub arn:aws:s3:::${UploadBucketName}/*
                  - !Sub arn:aws:s3:::${ProcessedBucketName}/*
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  # 🧠 4. Lambda Function
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: image-resizer
      Handler: resize.lambda_handler
      Runtime: python3.11
      Timeout: 10
      MemorySize: 256
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref ArtifactBucketName
        S3Key: !Ref ArtifactKey
      Environment:
        Variables:
          SOURCE_BUCKET: !Ref UploadBucketName
          DEST_BUCKET: !Ref ProcessedBucketName

  # 🔁 5. Permission to allow S3 to trigger Lambda
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::${UploadBucketName}

  # 🔔 6. Add S3 Notification to trigger Lambda on .jpg upload
  S3EventNotification:
    Type: AWS::S3::BucketNotification
    Properties:
      Bucket: !Ref UploadBucket
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .jpg
            Function: !GetAtt LambdaFunction.Arn

Outputs:
  UploadBucketName:
    Value: !Ref UploadBucketName
  ProcessedBucketName:
    Value: !Ref ProcessedBucketName
  LambdaFunctionName:
    Value: !Ref LambdaFunction
