AWSTemplateFormatVersion: '2010-09-09'
Description: Image Upload and Processing Pipeline with S3 and Lambda

Parameters:
  UploadBucketName:
    Type: String
    Description: Name of the raw image upload S3 bucket

  ProcessedBucketName:
    Type: String
    Description: Name of the processed/resized image S3 bucket

  ArtifactBucketName:
    Type: String
    Description: Bucket name where the Lambda zip is stored

  ArtifactKey:
    Type: String
    Description: Path to the Lambda function zip file in S3

Resources:
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref UploadBucketName

  ProcessedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ProcessedBucketName

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: photoProcessorLambdaRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3AccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  ImageProcessorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ImageResizerFunction
      Handler: resize.lambda_handler
      Runtime: python3.11
      Timeout: 10
      Role: !GetAtt LambdaRole.Arn
      Code:
        S3Bucket: !Ref ArtifactBucketName
        S3Key: !Ref ArtifactKey
      Environment:
        Variables:
          SOURCE_BUCKET: !Ref UploadBucketName
          DEST_BUCKET: !Ref ProcessedBucketName

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ImageProcessorFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId

Outputs:
  UploadBucket:
    Description: The raw image upload S3 bucket
    Value: !Ref UploadBucketName

  ProcessedBucket:
    Description: The processed image output S3 bucket
    Value: !Ref ProcessedBucketName

  LambdaFunctionName:
    Description: Name of the Lambda function
    Value: !Ref ImageProcessorFunction
