AWSTemplateFormatVersion: "2010-09-09"
Description: Serverless image processing pipeline using S3 and Lambda

Parameters:
  UploadBucketName:
    Type: String
    Default: my-photo-blog-uploads-hauwa
  ProcessedBucketName:
    Type: String
    Default: my-photo-blog-processed-hauwa

Resources:

  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref UploadBucketName

  ProcessedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ProcessedBucketName

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: image-processing-lambda-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: image-resizer
      Handler: resize.lambda_handler
      Runtime: python3.11
      Timeout: 10
      MemorySize: 256
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: hauwa-lambda-artifacts  # ✅ This must already exist in S3!
        S3Key: resize.zip                 # ✅ This must already be uploaded by GitHub Actions
      Environment:
        Variables:
          SOURCE_BUCKET: !Ref UploadBucketName
          DEST_BUCKET: !Ref ProcessedBucketName

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LambdaFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !GetAtt UploadBucket.Arn

Outputs:
  UploadBucket:
    Description: Raw image upload bucket
    Value: !Ref UploadBucketName

  ProcessedBucket:
    Description: Resized images output bucket
    Value: !Ref ProcessedBucketName

  LambdaFunctionName:
    Description: Lambda function that resizes images
    Value: !Ref LambdaFunction
