AWSTemplateFormatVersion: '2010-09-09'
Description: Image Upload and Resize Pipeline (No API Gateway)

Parameters:
  UploadBucketName:
    Type: String
    Description: Bucket for user-uploaded images

  ProcessedBucketName:
    Type: String
    Description: Bucket for resized images

  ArtifactBucketName:
    Type: String
    Description: Bucket holding Lambda zip

  ArtifactKey:
    Type: String
    Description: Path to Lambda zip in S3

Resources:
  UploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref UploadBucketName

  ProcessedBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref ProcessedBucketName

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "photoProcessorLambdaRole-${AWS::StackName}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaS3LogsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  ImageProcessorFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "ImageResizerFunction-${AWS::StackName}"
      Handler: resize.lambda_handler
      Runtime: python3.11
      Timeout: 10
      Role: !GetAtt LambdaRole.Arn
      Code:
        S3Bucket: !Ref ArtifactBucketName
        S3Key: !Ref ArtifactKey
      Environment:
        Variables:
          SOURCE_BUCKET: !Ref UploadBucketName
          DEST_BUCKET: !Ref ProcessedBucketName

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ImageProcessorFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId

Outputs:
  UploadBucket:
    Description: Raw image upload bucket
    Value: !Ref UploadBucketName

  ProcessedBucket:
    Description: Resized image output bucket
    Value: !Ref ProcessedBucketName

  LambdaFunctionName:
    Description: Lambda Function that resizes the image
    Value: !Ref ImageProcessorFunction
