name: Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Deploy CloudFormation Stack (Buckets & Infra)
      run: |
        aws cloudformation deploy \
          --template-file templates/cloudformation.yaml \
          --stack-name ImageUploadStack \
          --capabilities CAPABILITY_NAMED_IAM
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-north-1

    - name: Zip Lambda code
      run: |
        cd lambda
        zip -r ../resize.zip .
        cd ..

    - name: Upload Lambda zip to S3
      run: |
        aws s3 cp resize.zip s3://my-photo-blog-uploads/lambda/resize.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-north-1
