name: Deploy to AWS

on:
  push:
    branches: [main]

env:
  AWS_REGION: eu-north-1
  UPLOAD_BUCKET: image-upload-raw-hauwa
  PROCESSED_BUCKET: image-upload-processed-hauwa
  ARTIFACT_BUCKET: my-photo-blog-uploads
  ARTIFACT_KEY: lambda/resize.zip

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies and zip Lambda
        run: |
          pip install pillow -t lambda/
          cd lambda
          zip -r ../resize.zip .

      - name: Upload Lambda to S3
        run: |
          aws s3 cp resize.zip s3://$ARTIFACT_BUCKET/$ARTIFACT_KEY
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file templates/cloudformation.yaml \
            --stack-name ImageUploadStack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              UploadBucketName=$UPLOAD_BUCKET \
              ProcessedBucketName=$PROCESSED_BUCKET \
              ArtifactBucketName=$ARTIFACT_BUCKET \
              ArtifactKey=$ARTIFACT_KEY \
            --region $AWS_REGION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}
