name: Deploy Image Upload Stack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-north-1
      ARTIFACT_BUCKET: image-upload-artifacts-hauwa
      ARTIFACT_KEY: lambda_function.zip

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file templates/cloudformation.yaml \
            --stack-name ImageUploadStack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              UploadBucketName=image-upload-raw-hauwa \
              ProcessedBucketName=image-upload-processed-hauwa \
              ArtifactBucketName=$ARTIFACT_BUCKET \
              ArtifactKey=$ARTIFACT_KEY \
            --region $AWS_REGION

      - name: Debug CloudFormation failure
        if: failure()
        run: |
          echo "=== CloudFormation Logs ==="
          aws cloudformation describe-stack-events \
            --stack-name ImageUploadStack \
            --region $AWS_REGION \
            --max-items 15
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
